/**
 * Global Type Definitions for CodeBro
 * This file centralizes all interfaces used across the CLI
 */

/**
 * Core message format for Grok API communication.
 */
export interface Message {
  role: 'system' | 'user' | 'assistant';
  content: string;
}

/**
 * Represents a file scanned from the local directory.
 */
export interface ScannedFile {
  path: string;
  relativePath: string;
  content: string;
  priority: number; // Higher number means more important
  summary?: string; // Optional short summary for "Shallow" scans
}

/**
 * Represents a specific code operation suggested by Grok.
 */
export interface CodeChange {
  file: string;
  action: 'CREATE' | 'MODIFY' | 'DELETE';
  content?: string; // Full content for CREATE/REPLACE
  patch?: string;   // Unified diff format for surgical MODIFIES
}

/**
 * Structured roadmap generated by Grok's initial analysis.
 */
export interface GrokAnalysisResult {
  summary: string;
  techStack: string[];
  issues: string[];
  plan: string[];
}